### ISSUE TITLE
Decide on documentation platform/style

### ISSUE THREAD

**Issue by GolanTrev** [Watts-Lab/daphme#13]
Explore and compare:
- [x] ReadTheDocs
- [x] Sphinx
- [x] Gitbook

what are these? how do I use them?

**Comment by Jacob-Lisner** [comment]
Sphinx is software to generate documentation
ReadTheDocs and Gitbook are hosting services for the documentation (ReadTheDocs is very compatible with Sphinx)
I got a Sphinx-ReadTheDocs setup working
