### ISSUE TITLE
Synthetic data with lat/lon and horizontal accuracy

### ISSUE THREAD

**Issue by GolanTrev** [Watts-Lab/daphme#16]
1000 users

**Comment by GolanTrev** [comment]
Use this point (in Web Mercator)  x: 4265699 y: -4392976 , and ADD the coordinates in the garden city, AND convert to lat/lon. Standard names found in constants.py, at most 0.5 Mb, >1 users, >1 day.

**Comment by thom-li** [comment]
s3://synthetic-raw-data/10-agents/sparse_trajectories.parquet
